import React, { useState } from 'react';
import { AreaChart, Area, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ComposedChart } from 'recharts';
import { ArrowUpRight, ArrowRight, Download, Zap, Leaf, ShieldCheck, Sun, Cpu, Thermometer, Droplets, Activity } from 'lucide-react';
import { downloadCsv } from '../utils/export';
export const formatTime = timestamp => new Date(timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
export function Metric({label, value, unit, detail, icon: Icon, accent}) { return <div className="metric-card"><div className="metric-label">{label}<Icon size={17}/></div><div className={`metric-value ${accent ? 'green-text' : ''}`}>{value}<span>{unit}</span></div><div className="metric-detail"><span><ArrowUpRight size={12}/></span>{detail}</div></div>; }
export function PacketTable({logs, detailed = false}) { return <div className="table-scroll"><table><thead><tr><th>Time</th><th>Device</th><th>Power</th><th>Expected</th>{detailed && <><th>Voltage</th><th>Current</th><th>Energy</th></>}<th>Verification</th><th>Confidence</th></tr></thead><tbody>{logs.map(log => <tr key={log.id}><td className="muted mono">{formatTime(log.timestamp)}</td><td><span className="device-cell"><Cpu size={14}/>{log.device_id.replace('SOLAR_', '').replaceAll('_', '-')}</span></td><td className="mono">{log.power.toFixed(2)} <span className="muted">W</span></td><td className="muted mono">{log.expected_power.toFixed(2)} W</td>{detailed && <><td>{log.voltage.toFixed(2)} V</td><td>{log.current.toFixed(2)} A</td><td>{log.energy_kwh?.toFixed(5)} kWh</td></>}<td><span className={`pill ${log.status === 'ANOMALY' ? 'warning' : 'success'}`}><i/>{log.status === 'ANOMALY' ? 'Flagged' : 'Verified'}</span></td><td className="muted mono">{(log.confidence * 100).toFixed(1)}%</td></tr>)}</tbody></table></div>; }
export default function DashboardView({latestPacket: p, summary: s, packetLogs, onMintCert, setActiveTab, isStreaming}) {
 const [range, setRange] = useState(60);
 const data = packetLogs.slice(0, range).reverse().map(log => ({ time: formatTime(log.timestamp), 'Reported power': log.power, 'Expected power': log.expected_power }));
 return <div className="page-enter"><div className="page-heading"><div><div className="eyebrow">YOUR ENERGY, VERIFIED.</div><h1>Workspace overview</h1><p>A clear view of your clean energy and the impact it creates.</p></div><button className="button secondary" onClick={() => downloadCsv(packetLogs, 'renewcred-telemetry')}><Download size={15}/> Export report</button></div>
 <div className="hero-banner"><div className="hero-copy"><span className="hero-kicker"><i className="status-dot"/> CLEAN ENERGY INTELLIGENCE</span><h2>Every watt tells a better story.</h2><p>Monitor your generation. Verify your impact.<br/>Bring your carbon journey together in one place.</p><button className="button dark" onClick={onMintCert}>Create a certificate <ArrowUpRight size={15}/></button></div><div className="energy-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="energy-orb"><Leaf size={52} strokeWidth={1.2}/></div><span className="art-tag tag-one"><Zap size={13}/> Clean energy</span><span className="art-tag tag-two"><ShieldCheck size={13}/> Verified impact</span><div className="art-grid"/></div></div>
 <div className="section-caption"><h3>Performance at a glance</h3><span><i className={isStreaming ? 'status-dot' : 'status-dot paused'}/>{isStreaming ? 'Updating live' : 'Updates paused'}</span></div>
 <div className="metrics-grid"><Metric label="Live generation" value={p.power.toFixed(2)} unit="W" detail="Latest simulated reading" icon={Zap}/><Metric label="Clean energy generated" value={s.total_energy_kwh.toFixed(5)} unit="kWh" detail="Verified readings only" icon={Sun}/><Metric label="Carbon avoided" value={s.total_co2_reduced_kg.toFixed(5)} unit="kg" detail="CO2 equivalent · 0.82 kg/kWh" icon={Leaf} accent/><Metric label="Verification rate" value={(s.verified_readings / s.total_readings * 100).toFixed(1)} unit="%" detail={`${s.verified_readings.toLocaleString()} readings approved`} icon={ShieldCheck}/></div>
 <div className="analytics-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h3>Energy generation</h3><p>Reported output against the physical baseline</p></div><select aria-label="Chart window" value={range} onChange={event => setRange(Number(event.target.value))}><option value={60}>Last 60 readings</option><option value={120}>Last 120 readings</option><option value={200}>All readings</option></select></div><div className="chart-legend"><span><i style={{background:'#239875'}}/>Reported power</span><span><i style={{background:'#b5c7be'}}/>Expected power</span><span className="chart-unit">Watts (W)</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:10,right:8,left:-22,bottom:0}}><defs><linearGradient id="powerFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#62b99b" stopOpacity={.3}/><stop offset="100%" stopColor="#62b99b" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eeefed" strokeDasharray="3 4"/><XAxis dataKey="time" minTickGap={75} tick={{fill:'#979994',fontSize:10}} tickLine={false} axisLine={false} dy={8}/><YAxis tick={{fill:'#979994',fontSize:10}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{border:'1px solid #e7e8e4',borderRadius:10,fontSize:12}}/><Area type="monotone" dataKey="Reported power" stroke="#239875" fill="url(#powerFill)" strokeWidth={2} isAnimationActive={false}/><Line type="monotone" dataKey="Expected power" stroke="#a6bcb1" strokeDasharray="4 4" dot={false} strokeWidth={1.5} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><div className="chart-footer"><ShieldCheck size={14}/> Power validated against P = V × I <span>1.5s refresh interval</span></div></section>
 <section className="panel diagnostics"><div className="panel-heading"><div><h3>Node health</h3><p>ESP32 solar monitoring</p></div><span className="icon-box"><Cpu size={17}/></span></div><div className="node-summary"><span className="node-icon"><RadioIcon/></span><div><strong>{p.device_id.replaceAll('_','-')}</strong><span><i className={isStreaming ? 'status-dot' : 'status-dot paused'}/>{isStreaming ? 'Receiving simulated telemetry' : 'Simulation paused'}</span></div></div><div className="diagnostic-rows">{[[Zap,'Voltage',`${p.voltage.toFixed(2)} V`],[Activity,'Current',`${p.current.toFixed(2)} A`],[Thermometer,'Temperature',`${p.temperature.toFixed(1)} °C`],[Droplets,'Humidity',`${p.humidity.toFixed(1)}%`],[Sun,'Irradiance',`${p.irradiance} W/m²`]].map(([Icon,label,value]) => <div key={label}><span><Icon size={14}/>{label}</span><strong className="mono">{value}</strong></div>)}</div><button className="text-button" onClick={() => setActiveTab('ai')}>View verification details <ArrowRight size={14}/></button></section></div>
 <section className="panel"><div className="panel-heading"><div><h3>Recent telemetry</h3><p>Your latest readings, automatically checked as they arrive.</p></div><button className="button subtle" onClick={() => setActiveTab('prediction-logs')}>View all logs <ArrowRight size={14}/></button></div><PacketTable logs={packetLogs.slice(0,6)}/><div className="table-footer"><span>Showing 6 of {packetLogs.length} buffered readings</span><span>Updated {formatTime(p.timestamp)}</span></div></section>
 </div>;
}
function RadioIcon(){return <Activity size={20}/>;}

