import React, { useEffect, useState } from 'react';
import { ShieldCheck, AlertTriangle, Activity, FileText, Download, Plus, Search, Leaf, ArrowUpRight, Zap } from 'lucide-react';
import { Metric, PacketTable, formatTime } from './DashboardView';
import { downloadCsv, downloadFile } from '../utils/export';
function Heading({title, description, children}) { return <div className="page-heading"><div><div className="eyebrow">RENEWCRED WORKSPACE</div><h1>{title}</h1><p>{description}</p></div>{children}</div>; }
export function AIVerificationView({summary: s, packetLogs, onTriggerAnomaly}) {
 return <div className="page-enter"><Heading title="Trust in every reading" description="Inspect the checks behind your clean energy data."><button className="button secondary" onClick={onTriggerAnomaly}><AlertTriangle size={15}/> Simulate anomaly</button></Heading><div className="metrics-grid three"><Metric label="Readings evaluated" value={s.total_readings.toLocaleString()} detail="Continuous telemetry evaluation" icon={Activity}/><Metric label="Verified readings" value={s.verified_readings.toLocaleString()} detail="Passed the physical consistency check" icon={ShieldCheck} accent/><Metric label="Flagged readings" value={s.anomaly_readings.toLocaleString()} detail="Excluded from carbon accounting" icon={AlertTriangle}/></div><div className="verification-banner"><ShieldCheck size={28}/><div><h3>Physics verification is running</h3><p>Demo rule engine · P = V × I · Simulated confidence scores · No external AI service connected</p></div><span className="pill success">Demo engine</span></div><section className="panel"><div className="panel-heading"><div><h3>Verification activity</h3><p>Decisions and their underlying physical checks</p></div></div><div className="audit-list">{packetLogs.slice(0,12).map(log => <div className="audit-row" key={log.id}><span className={`audit-icon ${log.status === 'ANOMALY' ? 'flagged' : ''}`}>{log.status === 'ANOMALY' ? <AlertTriangle size={17}/> : <ShieldCheck size={17}/>}</span><div><strong>{log.status === 'ANOMALY' ? 'Power mismatch detected' : 'Reading verified'}</strong><p>{log.reason}</p></div><time>{formatTime(log.timestamp)}</time></div>)}</div></section></div>;
}
export function PredictionLogsView({packetLogs}) {
 const [query,setQuery] = useState(''); const [status,setStatus] = useState('all');
 const logs = packetLogs.filter(log => (status === 'all' || log.status === status) && `${log.device_id} ${log.id} ${log.reason}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="page-enter"><Heading title="Telemetry logs" description="A continuous audit trail of every simulated sensor reading."><button className="button secondary" onClick={() => downloadCsv(logs,'renewcred-filtered-logs')}><Download size={15}/> Export CSV</button></Heading><section className="panel"><div className="filter-bar"><label className="search-input"><Search size={16}/><input placeholder="Search devices, IDs or verification reasons…" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Filter verification status" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="NORMAL">Verified</option><option value="ANOMALY">Flagged</option></select><span className="muted">{logs.length} readings</span></div><PacketTable logs={logs} detailed/>{!logs.length && <div className="empty-state">No readings match your filters.</div>}</section></div>;
}
const seedCertificates = Array.from({length:6},(_,index)=>({id:`RCC-DEMO-2026-${88102+index}`,energy:18.2+index*3.17,credits:(18.2+index*3.17)*.82/1000,timestamp:new Date(Date.now()-index*86400000).toISOString()}));
export function CertificateView({certificates,summary,onMintCert,notify}) {
 const all = [...certificates,...seedCertificates];
 const download = cert => { downloadFile(JSON.stringify({...cert,mode:'demonstration',blockchain_transaction:null,co2_kg:cert.energy*.82},null,2),`${cert.id}.json`,'application/json'); notify('Demo certificate downloaded.'); };
 return <div className="page-enter"><Heading title="Your impact, documented" description="Organize and export your demonstration carbon certificates."><button className="button dark" onClick={onMintCert}><Plus size={15}/> Create certificate</button></Heading><div className="verification-banner"><Leaf size={28}/><div><h3>{summary.total_carbon_credits.toFixed(7)} estimated carbon credits</h3><p>Derived from verified simulated readings. These demo certificates are not issued on a blockchain or certified for trading.</p></div></div><div className="certificate-grid">{all.map(cert=><article className="certificate-card" key={cert.id}><div className="certificate-top"><span className="certificate-icon"><FileText size={23}/></span><span className="pill neutral">Demo certificate</span></div><small>RENEWABLE ENERGY CERTIFICATE</small><h3>{cert.id}</h3><p>Rooftop solar · Chennai, India</p><div className="certificate-values"><div><small>Clean energy</small><strong>{cert.energy.toFixed(4)} <span>kWh</span></strong></div><div><small>Carbon avoided</small><strong>{(cert.energy*.82).toFixed(4)} <span>kg</span></strong></div></div><div className="certificate-footer"><time>{new Date(cert.timestamp).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</time><button className="text-button" onClick={()=>download(cert)}>Download <Download size={14}/></button></div></article>)}</div></div>;
}
const projects = ['Chennai rooftop solar','Coimbatore solar collective','Bengaluru clean charging','Madurai community solar','Pune renewable microgrid','Hyderabad solar park'];
export function MarketplaceView({notify,isStreaming,owned=[],setOwned=()=>{},retired=[],setRetired=()=>{}}) {
 const [tick,setTick] = useState(0);
 useEffect(()=>{if(!isStreaming)return;const timer=setInterval(()=>setTick(value=>value+1),1500);return ()=>clearInterval(timer);},[isStreaming]);
 const listings = projects.map((project,index)=>({id:index,project,credits:.12+index*.073,price:1250+index*85+Math.sin(tick*.15+index)*12}));
 return <div className="page-enter"><Heading title="A market for positive impact" description="Explore renewable projects and try the carbon credit trading workflow."/><div className="market-banner"><span className="hero-kicker">DEMO CARBON MARKET</span><h2>Support a cleaner tomorrow.</h2><p>Discover projects, build a sample portfolio, and explore credit retirement.</p><span className="pill neutral">Simulated prices · No real transactions</span></div><section className="panel"><div className="panel-heading"><div><h3>Available projects</h3><p>Indicative INR price per credit · Updated with the demo stream</p></div><span className="pill success">{listings.length} projects</span></div><div className="table-scroll"><table><thead><tr><th>Project</th><th>Source</th><th>Available credits</th><th>Price / credit</th><th/></tr></thead><tbody>{listings.map(item=><tr key={item.id}><td><span className="device-cell"><span className="project-icon"><SunIcon/></span><strong>{item.project}</strong></span></td><td><span className="pill neutral">Renewable energy</span></td><td className="mono">{item.credits.toFixed(5)}</td><td className="mono">?{item.price.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td><button className="button secondary small" disabled={owned.some(credit=>credit.id===item.id)} onClick={()=>{setOwned(items=>[...items,item]);notify('Demo credits added to your sample portfolio.');}}>{owned.some(credit=>credit.id===item.id)?'Added':'Buy demo credits'}<ArrowUpRight size={13}/></button></td></tr>)}</tbody></table></div></section><section className="panel portfolio-panel"><div className="panel-heading"><div><h3>Your sample portfolio</h3><p>{owned.length} purchased projects · {retired.length} retired</p></div></div>{!owned.length?<div className="empty-state"><Leaf size={24}/><p>Buy demo credits from a project to start your portfolio.</p></div>:owned.map(item=><div className="portfolio-row" key={item.id}><div><strong>{item.project}</strong><p>{item.credits.toFixed(5)} credits · Demo holding</p></div><button className="button secondary small" disabled={retired.includes(item.id)} onClick={()=>{setRetired(items=>[...items,item.id]);notify('Demo credits retired in your sample portfolio.');}}>{retired.includes(item.id)?'Retired':'Retire demo credits'}</button></div>)}</section></div>;
}
function SunIcon(){return <Zap size={16}/>;}

